INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (1, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (2, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (3, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (4, 0, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (5, 0, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (6, 6, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (7, 6, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (8, 4, '2021-07-17 14:56:12', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (9, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (10, 4, '2021-07-17 19:50:43', 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (11, 0, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (12, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (13, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (14, 6, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (15, 1, '2021-07-21 20:47:57', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (16, 2, '2021-07-21 20:55:33', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (17, 1, '2021-07-21 21:59:35', 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (18, 2, '2021-07-21 22:00:25', 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (19, 6, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (20, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (21, 4, '2021-07-21 22:49:16', 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (22, 6, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (23, 6, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (24, 1, '2021-07-23 20:00:26', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (25, 2, '2021-07-23 20:09:03', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (26, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (27, 0, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (28, 6, null, 3);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (29, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (30, 1, '2021-07-24 16:17:24', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (31, 4, '2021-07-24 16:17:35', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (32, 1, '2021-07-24 16:17:53', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (33, 2, '2021-07-24 16:23:28', 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (34, 6, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (35, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (36, 0, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (37, 6, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (38, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (39, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (40, 0, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (41, 0, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (42, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (43, 6, null, 2);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (44, 0, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (45, 0, null, null);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (46, 0, null, null);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (47, 6, null, 1);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (48, 0, null, null);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (49, 0, null, null);
INSERT INTO hfn.agent_activity_log (id, log_event, timestamp, agent_id) VALUES (50, 0, null, null);