package org.heartfulness.avtc.model.enums;

public enum CallerCategory {
    INDIVIDUALS_WITH_COVID_AFFECTED_FAMILIES,
    CAREGIVERS_AND_FRONT_LINE_WORKERS,
    WELL_WISHERS_WHO_WISH_TO_HELP_COVID_AFFECTED_FAMILIES,
    SURVIVORS_OF_TRAUMA,
    INDIVIDUALS_WITH_SUICIDAL_TENDENCIES;
}
